const Skills = () => {
 return (
  <div className="flex flex-col justify-between min-w-[5rem] text-sm xs:w-min marquee">
   <div className="flex flex-col items-center marquee-inner">
    <span>Next</span>
    <span>Javascript</span>
    <span>Tailwind</span>
    <span>Typescript</span>
    <span>Sass</span>
    <span>CSS3</span>
    <span>HTML5</span>
    <span>Figma</span>
    <span>React</span>
    <span>Node</span>
    <span>Postgres</span>
    <span>Git</span>
    <span>Heroku</span>
    <span>Netlify</span>
    <span>Vercel</span>
    <span>Prisma</span>
    <span>Next</span>
    <span>Javascript</span>
    <span>Tailwind</span>
    <span>Typescript</span>
    <span>Sass</span>
    <span>CSS3</span>
    <span>HTML5</span>
    <span>Figma</span>
    <span>React</span>
    <span>Node</span>
    <span>Postgres</span>
    <span>Git</span>
    <span>Heroku</span>
    <span>Netlify</span>
    <span>Vercel</span>
    <span>Prisma</span>
    <span>Next</span>
    <span>Javascript</span>
    <span>Tailwind</span>
    <span>Typescript</span>
    <span>Sass</span>
    <span>CSS3</span>
    <span>HTML5</span>
    <span>Figma</span>
    <span>React</span>
    <span>Node</span>
    <span>Postgres</span>
    <span>Git</span>
    <span>Heroku</span>
    <span>Netlify</span>
    <span>Vercel</span>
    <span>Prisma</span>
    <span>Next</span>
    <span>Javascript</span>
    <span>Tailwind</span>
    <span>Typescript</span>
    <span>Sass</span>
    <span>CSS3</span>
    <span>HTML5</span>
    <span>Figma</span>
    <span>React</span>
    <span>Node</span>
    <span>Postgres</span>
    <span>Git</span>
    <span>Heroku</span>
    <span>Netlify</span>
    <span>Vercel</span>
    <span>Prisma</span>
   </div>
  </div>
 );
};

export default Skills;
